services:
  postgres:
    container_name: pg-mytt
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'pgpass'
    ports:
      - 5432:5432
  keycloak:
    container_name: keycloak-mytt
    image: "quay.io/keycloak/keycloak:24.0.5"
    ports:
      - "8000:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    #    volumes:
    #      - ./keycloak/realm-data.json:/opt/keycloak/data/import/realm-data.json
    command: start-dev --import-realm
#    command: start-dev --import-realm